import React from 'react'

export const   About  = () => (

    <div>
        <h2>About</h2>
        <p>India has an extremely rich craft tradition, distinguished by great aesthetics and mixed art history. Difficult designs, patterns, painfully crafted monuments, temples and sculptures, all are magnificent masterpieces of craftsmanship. All Indian crafts and patterns were mostly representations of everyday living, socio political conditions and palace and court scenes. Archaeological studies have revealed that the period of manufacture, for a given handicraft item can be explained from its production technique, patterns and materials used. 
          The tradition and culture of a particular place is reflected by its handicrafts items. It carries tales of ancient times of the kings and queens, and tells stories of its heritage. Wooden handicrafts like carved figures, painted figure, chess board, animal figure and other Indian Handicraft Items of wood are designed aesthetically by the skilled craftsman. If you take a closer look at these wooden handicraft items, they represent the spirit of Indian Craftsmanship in true spirits along with style and beauty. They are widely used as gift articles due to their attractive looks.</p>
        <p>Today, handicraft is flourishing in the Indian industry because of its rich cultural heritage and diversity. Indian handicraft items ranges from wooden stone, metal, glass, bamboo, cane, clay, terracotta ceramics, and textiles. Majority of its production is exported to different countries; the most popular items in Indian handicrafts are brass ware, pen holder, vases, candle stand, Christmas items, ceramic pots, and other products of paper. Different states of India like north eastern Manipur, Tripura, Northern States of Rajasthan, Gujarat, Kashmir or the southern part, Maharashtra, Tamil Nadu, and Kerala are popular for its handicraft collection. Each States offers a wide range of handicrafts, with its own identity. These handicraft items represent quality craftsmanship. Metal handicrafts metals like iron, silver, gold, white metal, sand stones and semi-precious stones which are embossed and carved with beautiful designs. From time to time handicraft trades and exhibitions are organized for handicraft lovers all over the world.</p>
        <p>India is one of the major suppliers of handicrafts to the global market. Highly labour intensive, and basically cottage based, the industry is more widespread in the rural and urban areas. The industry provides a livelihood for more than 6 million artisans including a big share of women artisans, and people from the weaker sections of the country. Indian Arts and Crafts of each age reflect the culture, traditions and happenings of that particular era. Every age, every dynasty, every empire has its influence and essence in the crafts belonging to those times, therefore making India's heritage diverse and culturally rich. Indian Traditional Jewellery, Beaded Jewellery, Tribal Jewellery, Phulkari art, Madhubani Paintings, Miniature Paintings, Tanjore Paintings, Warli Paintings, Cotton Fabrics, Jute Products (Bags, Mats) Bamboo & Cane Products (Furniture, Decorative), Glass Crafts, Stone & Marble Crafts, Leather Crafts (Shoes, Bags) Shell Crafts (Jewellery, Decorative) are some of the major Indian Crafts products. Apart from these there are huge variety of Crafts Products are available in both Indian and International market. 
            There is huge demand for Indian Crafts Products in both domestic and international market. Major part of Crafts Industry is dominated by small & medium scale enterprises. To deliver quality products & match the demand & supply, there is need of greater technological support & innovativeness in industry. Crafts are an integral part of Indian Culture and will continue to play a major role in the Cultural and Economic well-being of India.</p>
    </div>


)